function loadFlavorTexts() {
	return {
		corridors:[
			"A short and dry corridor.",
			"Rocks creak as you walk down the hall.",
			"Something muddy squishes under your feets.",
			"It's pitch black here.",
			"Unreadable inscriptions runs along the corridor walls.",
			"The wind howl along the narrow corridor.",
			"Candles are along the walls.",
			"Your image is reflected by thousands of crystals on the wall.",
			"The walls and the floor were scratched by some beast.",
			"You feel the urge to leave this narrow room as soon as possible.",
			"You hear a door slamming.",
			"Your footsteps echo throughout the dungeon.",
			"Ink stains trickle down the stairs.",
			"Green grass pops out between the floor tiles.",
			"The wooden door closes behind you.",
		],
		rooms:[
			"A dim light is filtering through the curtains.",
			"A huge chandelier on the ceiling lights up the room.",
			"The floor is so clean that it reflects your image.",
			"Some heads are hanging from the ceiling.",
			"There is a huge statue of a cube in the middle of the room.",
			"Four columns are projecting their long shadows on the floor.",
			"You step in a huge marble amphitheater.",
			"You hear some whispers.",
			"There are fresh bloodstains on the woody floor.",
			"This room stench is unbearable.",
			"The walls of this room are gold plated.",
			"You feel fatigued and this is not a good sign.",
			"You managed to dodge a dart fired by a statue.",
			"Your throat suddenly gets dry.",
			"Eerie glows of torches are speckling the dark walls of the cellar.",
			"On the gigantic apse in ruin a purple bonfire is still burning.",
			"Multiple secular mud prints head to the recessed altar.",
			"Only the faint shimmer of blades breaks through the dark armory.",
			"A mysterious disturbing buzz fills the cave, invading your brain.",
			"Weird machines and gliphes stamps are stocked in the workroom.",
			"A rusty knife is still stucked in a boar stinking carcass, lying on the table.",
			"Faded ink sketches of letal creatures and traps are hanging on the walls.",
			"By going through the charming courtyard, warm sun rays pacify your spirit.",
			"Rivolets of a thick black fluid gush from the wall of the romboid room.",
			"A maze of mirrors hides the way out. Your trembling legs start moving...",
			"Heap of bones lie tidy in the vault corners, attended by peaceful statues.",
		]
	};
}