/* exported loadFlavorTexts */

function loadFlavorTexts() {
	return {
		corridors:[
			"A short and dry corridor.",
			"Rocks creak as you walk down the hall.",
			"Something muddy squishes under your feets.",
			"It's pitch black here.",
			"Unreadable inscriptions runs along the corridor walls.",
			"The wind howl along the narrow corridor.",
			"Candles are along the walls.",
			"Your image is reflected by thousands of crystals on the wall.",
			"The walls and the floor were scratched by some beast.",
			"You feel the urge to leave this narrow room as soon as possible.",
			"You hear a door slamming.",
			"Your footsteps echo throughout the dungeon.",
			"Ink stains trickle down the stairs.",
			"Green grass pops out between the floor tiles.",
			"The wooden door closes behind you.",
			"Pieces of glass, soaked by black ink, are scattered along dark corridor.",
			"This corridor is so dark that you begin doubting of your own existence.",
			"Water drips from stalactites.",
			"Green ooze covers the walls.",
			"Ceiling is so low you have to crawl.",
			"This dirt tunnel is about to collapse.",
			"Broken stone gates used to block intruders.",
			"Hundreds of bats call this place home.",
			"You smell burnt wood.",
		],
		rooms:[
			"A dim light is filtering through the curtains.",
			"A huge chandelier on the ceiling lights up the room.",
			"The floor is so clean that it reflects your image.",
			"Some heads are hanging from the ceiling.",
			"There is a huge statue of a cube in the middle of the room.",
			"Four columns are projecting their long shadows on the floor.",
			"You step in a huge marble amphitheater.",
			"You hear some whispers.",
			"There are fresh bloodstains on the woody floor.",
			"This room stench is unbearable.",
			"The walls of this room are gold plated.",
			"You feel fatigued and this is not a good sign.",
			"You managed to dodge a dart fired by a statue.",
			"Your throat suddenly gets dry.",
			"Eerie glows of torches are speckling the dark walls of the cellar.",
			"On the gigantic apse in ruin, a purple bonfire is still burning.",
			"Multiple secular mud prints head to the recessed altar.",
			"Only the faint shimmer of blades breaks through the dark armory.",
			"A mysterious disturbing buzz fills the cave, invading your brain.",
			"Weird machines and glyphs stamps are stocked in the workroom.",
			"A rusty knife is still stuck in a boar stinking carcass, lying on the table.",
			"Faded ink sketches of lethal creatures and traps are hanging on the walls.",
			"By going through the charming courtyard, warm sun rays pacify your spirit.",
			"Rivulets of a thick black fluid gush from the wall of the rhomboid room.",
			"A maze of mirrors hides the way out. Your trembling legs start moving...",
			"Heap of bones lies tidy in the vault corners, attended by peaceful statues.",
			"Amazing sea-green luminescences reflect in the almost dry pond of the cave.",
			"Something in the room appears so familiar to you... A thrill crosses your skin.",
			"The countless leaves of a titanic oak are piled up in the court floor.",
			"You enter in a room with no openings welcomed by a fierce stink of death.",
			"Every angle is rounded with plaster. Hounds?", // Tindalos hounds of course - Preuk
			"A small stream runs from a crack in the wall.",
			"This looks like a giant chessboard.",
			"Echoes suggest a much bigger room.",
			"Your mouth fills with the taste of... strawberry?.",
			"Above is a night sky with unknown constellations.",
			"Oversize furniture make you feel insignificant.",
			"You hear a strange hum from the ground.",
		]
	};
}