/* exported loadPlaceholders */

function loadPlaceholders() {
	return {
		adventureHeader:[
			"{nameLine} the {heroClass} in",
			"The {heroClass} {nameLine} in"
		],
		villainName:[
			"Dark Lord",
			"Hydra",
			"Chimera",
			"Bloody Dragon",
			"Basilisk",
			"Minotaur",
			"King Goblin",
			"Mists Queen",
			"Butcher",
			"Cyclop",
			"Demon",
			"Red Oni",
			"Devil",
			"Unnamed",
			"Dark One",
			"Destroyer",
			"Souls Thief",
			"Dark Lady",
			"Fallen Angel",
			"Mad Valkyrie",
			"Cruel Gorgon",			
			"Usurper",
		],
		winningScene:[
			"You did it!",
			"You are carried in triumph to the capital!",
			"You won!",
			"You are a legend!",
			"You are a hero!",
			"You will always be remembered!",
		],
		goodGuyName:[
			"King",
			"Prince",
			"Princess",
			"Great Saviour",
			"Sarge",
			"Queen",
			"Old Sage",
			"Guardian",
			"Cleric",
			"Counsellor",
			"Hermit",
		],
		goodGuyRelativeName:[
			"Friend",
			"Wife",
			"Son",
			"Child",
			"Lover",
		],
		bossKey:[
			"Skull Key",
			"Bloody Key",
			"Invisibility Orb",
			"Sacred Key",
			"Discovery Scroll",
			"Flaming Gem",
			"Lost Key",
			"Diamond Rhombus",
			"Rupture Seal",
			"Recall Seal",
			"Trauma Orb",
			"Frozen Heart",
			"Spirit Stone",
			"Forgotten Stamp",
		],
		placeName:[
			"Island",
			"Valley",
			"Temple",
			"Land",
			"City",
			"Capital",
			"Mountain",
			"Lake",
			"Forest",
			"Abbey",
			"Swamp",
			"Catacomb",
			"Borough",
			"Mill",
			"Desert",
			"Shore",
			"Hill",
			"Woods",
			"Village",
			"Castle",
			"Cliff",
		],
		explorerName:[
			"Archaeologist",
			"Explorer",
			"Spy",
			"Hunter",
			"Scholar",
			"Detective",
			"Recruit",
			"Wanderer",
			"Scribe",
			"Chronicler",
		],
		documentName:[
			"Scroll",
			"Inscription",
			"Document",
			"Message",
			"Register",
			"Engraving",
		],
		victimName:[
			"Kid",
			"Adventurer",
			"Girl",
			"Boy",
			"Man",
			"Woman",
			"Elder"
		],
		epicWeapon:[
			"Void Cutter",
			"Black Shythe",
			"Bloody Claw",
			"Black Blade"
		],
		epicWeaponPart:[
			"Shard",
			"Part",
			"Piece"
		],
	};
}