var INDEX=[
	"[CODEX-Events] Anomaly - The Couple: 2 level 0 enemy in the depth of the dungeon.",
	"[CODEX-Events] Anomaly - The Little Lost One: A level 0 enemy lost in the depth of the dungeon.",
	"[CODEX-Events] Anomaly - The Lost Privacy: A level 2 enemy in an optional room.",
	"[CODEX-Events] Anomaly - The One In Late: A level 1 enemy lost in the depth of the dungeon.",
	"[CODEX-Events] Bonus - The Clover: It may bring good luck in your future adventures...",
	"[CODEX-Events] Bonus - The Clown: Pay him/her to learn cool stunts!",
	"[CODEX-Events] Bonus - The Magic Tree: It grows a healing fruit after some time.",
	"[CODEX-Events] Bonus - The Mirror: Go back to this room using an item.",
	"[CODEX-Events] Bonus - The NPC: Learn about the Stampadia lore by Stampadians.",
	"[CODEX-Events] Bonus - The Powder Magazine: Choose between 2 room-size based weapons.",
	"[CODEX-Events] Bonus - The Random Item: A random bonus item.",
	"[CODEX-Events] Bonus - The Saint: They will help you when you're in danger.",
	"[CODEX-Events] Bonus - The Shop: Pay gold or other valuables for useful items.",
	"[CODEX-Events] Bonus - The Teleports: Teleport from a room to another.",
	"[CODEX-Events] Bonus - The Wildness (bad): Earn a debuff after fighting an enemy.",
	"[CODEX-Events] Bonus - The Wildness (good): Earn a buff after fighting an enemy.",
	"[CODEX-Events] Filler (easy) - The One (1): One level 1 enemy.",
	"[CODEX-Events] Filler (easy) - The One (2): One level 1 enemy.",
	"[CODEX-Events] Filler (easy) - The Pair: Two level 0 enemies.",
	"[CODEX-Events] Filler (easy) - The Weak: One level 0 enemy.",
	"[CODEX-Events] Filler (hard) - The Strong Pair: Two level 2 enemies.",
	"[CODEX-Events] Filler (hard) - The Weak Pair: Two level 1 enemies.",
	"[CODEX-Events] Filler (medium) - The One (1): One level 2 enemy.",
	"[CODEX-Events] Filler (medium) - The One (2): One level 2 enemy.",
	"[CODEX-Events] Filler (medium) - The One: One level 2 enemy.",
	"[CODEX-Events] Filler (medium) - The Pair: Two level 1 enemies.",
	"[CODEX-Events] Filler (medium) - The Swarm: Three level 0 enemy.",
	"[CODEX-Events] Filler (very hard) - The Critters: Five level 0 enemy.",
	"[CODEX-Events] Filler (very hard) - The Deadly Sip: Gain all your health... or die.",
	"[CODEX-Events] Filler (very hard) - The One: One Level 4 enemy.",
	"[CODEX-Events] Helper - The Insurance: Pay Gold/XP for HP.",
	"[CODEX-Events] Helper - The Junk Shop: Trade your class item for full health.",
	"[CODEX-Events] Main quest - The Boss Battle: Beat the boss.",
	"[CODEX-Events] Main quest - The Broken Key: Collect the key parts and beat the boss.",
	"[CODEX-Events] Main quest - The Curse: Beat the boss and try to get rid of your curse.",
	"[CODEX-Events] Main quest - The Enchantment: Find an NPC lost in the dungeons to make your final battle easier.",
	"[CODEX-Events] Main quest - The Escort: Escort the good guy near the boss and fight.",
	"[CODEX-Events] Main quest - The Gang: Beat a sequence of enemies.",
	"[CODEX-Events] Main quest - The Great Old Ones: Beat the boss before being corrupted by madness.",
	"[CODEX-Events] Main quest - The Investigation: Investigate who the impostor may be and eliminate him.",
	"[CODEX-Events] Main quest - The Kidnapping: Fight the boss, free the kidnapped, and return it.",
	"[CODEX-Events] Main quest - The Lost Item: Return an item to NPC and unlock the boss and fight.",
	"[CODEX-Events] Main quest - The Missing Familiar: Find the familiar to get your missing skill back and kill the boss.",
	"[CODEX-Events] Main quest - The Missing Key: Find the key and beat the boss.",
	"[CODEX-Events] Main quest - The Moral Compass: Do good or bad things and trigger a different ending.",
	"[CODEX-Events] Main quest - The Necromancer: Someone is trying to bring the evil back.",
	"[CODEX-Events] Main quest - The Spell: Break the spell and kill the bad guy.",
	"[CODEX-Events] Main quest - The Suicide Mission: Fight 2 bosses at once, or...",
	"[CODEX-Events] Main quest - The Test: Beat the boss and get a better ending if you don't use your class item.",
	"[CODEX-Events] Main quest - The Twins: Fight a 2-stages boss.",
	"[CODEX-Events] Main quest - The War: Conquer the dungeon and beat the leader.",
	"[CODEX-Events] Malus - The Last Fight (1): An enemy will challenge you on your way back.",
	"[CODEX-Events] Malus - The Last Fight (2): An enemy will challenge you on your way back.",
	"[CODEX-Events] Malus - The Loop Rooms: It will teleport you to the starting room.",
	"[CODEX-Events] Malus - The Mercenary: Eliminate an enemy or pay The Mercenary to do that.",
	"[CODEX-Events] Malus - The Random Trap: Dodge a trap rolling a die.",
	"[CODEX-Events] Malus - The Small Horn: It may bring bad luck in your future adventures...",
	"[CODEX-Events] Malus - The Switch Trap: Step on a trap to get injured.",
	"[CODEX-Events] Malus - The Teleport Trap: It will teleport you to a room with an enemy.",
	"[CODEX-Events] Malus - The Timed Traps: Defuse it with the right timing or it will trigger!",
	"[CODEX-Events] Malus - The Witch: Pay her or she will curse you!",
	"[CODEX-Events] Storyline - The End Of Stampadia: Discover how Stampadia ended.",
	"[CODEX-Events] Storyline - The Rests: Finds from the world of stampadia.",
	"[CODEX-Events] Subquest - The Altar: Sacrify important resources for other advantages.",
	"[CODEX-Events] Subquest - The Architect: Beat him to get one of his items.",
	"[CODEX-Events] Subquest - The Barman: Pay gold for health or a short mission.",
	"[CODEX-Events] Subquest - The Beastcrafters: A simple trading card game Stampadians used to play. Buy or find new cards and play.",
	"[CODEX-Events] Subquest - The Bloody Gambler: Bet HP, roll a die and you may win more HP.",
	"[CODEX-Events] Subquest - The Broken Teleport: Solve the riddle to reach an item.",
	"[CODEX-Events] Subquest - The Elemental Chest: Find the 2 elemental keys and open a chest containing equipment.",
	"[CODEX-Events] Subquest - The Fountains: Decide between two effects.",
	"[CODEX-Events] Subquest - The Gambler: Bet Gold, roll a die and you may win more gold.",
	"[CODEX-Events] Subquest - The Guardians: Kill 2 mini-boss and earn bonus XPs.",
	"[CODEX-Events] Subquest - The Key And The Chest (good): Find the key and open one good chest.",
	"[CODEX-Events] Subquest - The Key And The Chests: Find the key and open one of two random chests.",
	"[CODEX-Events] Subquest - The Landslide: Free a room from rubbles or prevent it from collapsing to get an reward.",
	"[CODEX-Events] Subquest - The Linked Rooms: Walk on a cell and enable another room effect.",
	"[CODEX-Events] Subquest - The Monk: Donate 1G to draw one room walls.",
	"[CODEX-Events] Subquest - The Murderer: Avenge the dead body or steal its gold?",
	"[CODEX-Events] Subquest - The Nothing: A teleport to a place that leaves you no choice.",
	"[CODEX-Events] Subquest - The Shapes Puzzle: Get the right shapes to solve the puzzle.",
	"[CODEX-Events] Subquest - The Sphynx: Give the right answer, meet the Sphynx and get your reward.",
	"[CODEX-Events] Subquest - The Tapeworm: Kill the monster to stop him digesting you.",
	"[CODEX-Events] Subquest - The Trainer: Face his test and earn gold.",
	"[CODEX-Events] Subquest - The Traitor: Kill the enemy to learn where the boss is lurking.",
	"[CODEX-Modifiers] Enemy - Blind: Enemies plays just 1 die.",
	"[CODEX-Modifiers] Enemy - Crippled: Enemies moves -1.",
	"[CODEX-Modifiers] Enemy - Fear: Enemies -1 a die of choice.",
	"[CODEX-Modifiers] Enemy - Haste: Enemies rerolls his 1s.",
	"[CODEX-Modifiers] Enemy - Stunned: Hero rerolls his 1s.",
	"[CODEX-Modifiers] Hero - Blind: Hero plays just 1 die.",
	"[CODEX-Modifiers] Hero - Fear: Hero -1 a die of choice.",
	"[CODEX-Modifiers] Hero - Paralysis: Hero moves -1.",
	"[CODEX-Modifiers] Terrain - Arena: Everybody rerolls his 1s.",
	"[CODEX-Modifiers] Terrain - Darkness: Everybody plays just 1 die.",
	"[CODEX-Modifiers] Terrain - Mud: Everybody moves -1.",
	"[CODEX-Modifiers] Terrain - Tall grass: Everybody -1 a die of choice.",
	"[CODEX-Heroes] Class - The Dwarf: A strong fighter trained on swinging a huge war hammer. It's equipped with a war hammer, leather armor, and a Mead item.",
	"[CODEX-Heroes] Class - The Ranger: An archer that learns from the beasts. It's equipped with a bow and a Focus item.",
	"[CODEX-Heroes] Class - The Rogue: An agile thief that tricks enemies. It's equipped with a lasso, a throwing knife, and a Frag bomb item.",
	"[CODEX-Heroes] Class - The Warrior: A balanced fighter who prefers melee attacks. It's equipped with a short sword, warrior boots, a small flask of cure, a throwing knife, and a Resurrection item.",
	"[CODEX-Heroes] Class - The Wizard: A powerful mage that fights from the distance. It's equipped with lightning spells, a teleport spell, a magic shield, a healing spell, and a Fireball item.",
	"[CODEX-Stuff] Beast - The Bat: It can scare you permanently.",
	"[CODEX-Stuff] Beast - The Bear: Makes you braver.",
	"[CODEX-Stuff] Beast - The Light Ball: It can blind you permanently.",
	"[CODEX-Stuff] Beast - The Moth: His spores can blind your enemies.",
	"[CODEX-Stuff] Beast - The Porcupine: Gives you thorns to cripple your enemies.",
	"[CODEX-Stuff] Beast - The Scorpion: It can stun you permanently.",
	"[CODEX-Stuff] Beast - The Snake: It can poison you permanently.",
	"[CODEX-Stuff] Beast - The Whirlwind: His colors can stun your enemies.",
	"[CODEX-Stuff] Equipment - Apple: Gain 1/2 max HP.",
	"[CODEX-Stuff] Equipment - Backflip: Flip a dice upside down.",
	"[CODEX-Stuff] Equipment - Big die: Perform 1 free action with activation power 5.",
	"[CODEX-Stuff] Equipment - Book: Lose 1 HP, deal 1 damage.",
	"[CODEX-Stuff] Equipment - Curse: Lose max HP -1, does nothing.",
	"[CODEX-Stuff] Equipment - Dash: Sacrifice XPs to skip the enemy turn.",
	"[CODEX-Stuff] Equipment - Epic Weapon: A weapon with many names. Deal 2 damage to all enemies in range 4.",
	"[CODEX-Stuff] Equipment - Fireball: Inflict 2 damage.",
	"[CODEX-Stuff] Equipment - Focus: Pay 2G and sum 2 dice values.",
	"[CODEX-Stuff] Equipment - Frag: A fragmentation bomb that damages 2 nearby enemies when getting damage.",
	"[CODEX-Stuff] Equipment - Grenade: Perform an ATK action by the current room size.",
	"[CODEX-Stuff] Equipment - Invisibility: For the next 3 enemy turns, discard all dice less than 6.",
	"[CODEX-Stuff] Equipment - Large die: Perform 1 free action with activation power 5.",
	"[CODEX-Stuff] Equipment - Lunge: Place dice on the same column.",
	"[CODEX-Stuff] Equipment - Mead: Discard one die, set the other one to 6.",
	"[CODEX-Stuff] Equipment - Mirror: Teleport back to the mirror room.",
	"[CODEX-Stuff] Equipment - Rage: Sacrifice XPs to strike a critical hit.",
	"[CODEX-Stuff] Equipment - Resurrection: Pay gold to resurrect once.",
	"[CODEX-Stuff] Equipment - Small die: Perform 1 free action with activation power 4.",
	"[CODEX-Stuff] Equipment - Smoke: Perform a MOVE action by the current room size.",
	"[CODEX-Stuff] Equipment - Sonic: Perform a DEF action by the current room size.",
	"[CODEX-Stuff] Equipment - Spin: Play dices in reverse order.",
	"[CODEX-Stuff] Equipment - Sweep: Place dice on the same row.",
	"[CODEX-Stuff] Equipment - Tactic: Sacrifice XPs to strike a two strong hits.",
	"[CODEX-Stuff] Equipment - Taunt: Sacrifice XPs to weaken an enemy attack.",
	"[CODEX-Stuff] Fountain - The Black Fountain: Lose 2 HP.",
	"[CODEX-Stuff] Fountain - The Clean Fountain: Gain 1 HP.",
	"[CODEX-Stuff] Fountain - The Fresh Fountain: Gain 2 HP.",
	"[CODEX-Stuff] Fountain - The Muddy Fountain: Lose 1 HP.",
	"[CODEX-Stuff] Item - Belt: Prevents the boss fear effect.",
	"[CODEX-Stuff] Item - Blue Coin: Gives you a random bad reward.",
	"[CODEX-Stuff] Item - Boots: Can slow down a boss.",
	"[CODEX-Stuff] Item - Diamond: Can blind a boss.",
	"[CODEX-Stuff] Item - Goggles: Prevents the boss blind effect.",
	"[CODEX-Stuff] Item - Helmet: Prevents the boss stun effect.",
	"[CODEX-Stuff] Item - Necklace: Can stun a boss.",
	"[CODEX-Stuff] Item - Pendant: Scares a boss.",
	"[CODEX-Stuff] Item - Red Coin: Gives you a random good reward.",
	"[CODEX-Stuff] Item - Shawl: Prevents the boss crippled effect.",
	"[CODEX-Stuff] Item - The Bag Of Gold: Gain 3 gold.",
	"[CODEX-Stuff] Item - The Heart Shard: Gain 1 HP.",
	"[CODEX-Stuff] Item - The Star Pin: Gain 1 XP.",
	"[CODEX-Stuff] Shape puzzle - The Bolt: Which shapes are the right ones?",
	"[CODEX-Stuff] Shape puzzle - The Coin With The Hole: Which shapes are the right ones?",
	"[CODEX-Stuff] Shape puzzle - The Compass: Which shapes are the right ones?",
	"[CODEX-Stuff] Shape puzzle - The Eye Of The Gods: Which shapes are the right ones?",
	"[CODEX-Stuff] Shape puzzle - The Glass Of Wine: Which shapes are the right ones?",
	"[CODEX-Stuff] Shape puzzle - The Home: Which shapes are the right ones?",
	"[CODEX-Stuff] Special room - The Blessed Room: Gain 1 HP.",
	"[CODEX-Stuff] Special room - The Poisonous Room: Lose 1 HP.",
	"[CODEX-Stuff] Test - Bravery: Skip a turn for gold.",
	"[CODEX-Stuff] Test - Calm: Discard a rolled 6 for gold.",
	"[CODEX-Stuff] Test - Mercy: Turn an enemy rolled 1 to a 6 for gold.",
	"[CODEX-Stuff] Trap - The Mimic: Lose 1 HP.",
	"[CODEX-Keywords] Keyword - City: Part of the The End Of Stampadia storyline.",
	"[CODEX-Keywords] Keyword - Computer: Part of the The End Of Stampadia storyline.",
	"[CODEX-Keywords] Keyword - End: Part of the The End Of Stampadia storyline.",
	"[CODEX-Keywords] Keyword - Ink: Part of the The End Of Stampadia storyline.",
	"[CODEX-Keywords] Keyword - Irony: Part of the The End Of Stampadia storyline.",
	"[CODEX-Keywords] Keyword - Luck: It may bring you good luck during your adventures...",
	"[CODEX-Keywords] Keyword - Press: Part of the The End Of Stampadia storyline.",
	"[CODEX-Keywords] Keyword - Spaceship: Part of the The End Of Stampadia storyline.",
	"[CODEX-Keywords] Keyword - Unluck: It may bring you bad luck during your adventures...",
	"[CODEX-Keywords] Keyword set - Golem: Beastcrafters collectable cards from 1 to 3.",
	"[CODEX-Keywords] Keyword set - Hellhound: Beastcrafters collectable cards from 1 to 3.",
	"[CODEX-Keywords] Keyword set - Manticore: Beastcrafters collectable cards from 1 to 3.",
	"[CODEX-Generator] Layout - The City: Large rooms inside, then the corridors, then mid rooms, and the starting room outside.",
	"[CODEX-Generator] Layout - The Classic: Fully randomized dungeons.",
	"[CODEX-Generator] Layout - The Crossing: Corridors inside, then the starting room, and large and mid rooms on the outside.",
	"[CODEX-Generator] Layout - The Halls: Starting room inside, then large and mid rooms, and corridors on the outside.",
	"[CODEX-Generator] Layout - The Hill: Large and mid rooms inside, then the corridors, and the starting room outside.",
	"[CODEX-Generator] Layout - The Maze: Starting room inside, then corridors and large and mid rooms on the outside.",
	"[CODEX-Generator] Roomset - The Sewers: A set of small rectangular rooms with 2 huge halls.",
	"[CODEX-Generator] Roomset - The Sewers: A set of small rectangular rooms with 2 huge halls.",
	"[CODEX-Generator] Roomset - The Stampadian: A set of multiple sized rooms.",
	"[CODEX-Generator] Roomset - The Towers: A set of small squared rooms and corridors.",
];
